import { getBonusLogoUrl } from '../../data/casinoLogos';

export interface CasinoData {
  slug: string;
  name: string;
  logo: string;
  banner: string;
  rating: number;
  playNowUrl: string;
  summary: string;
  pros: string[];
  cons: string[];
  trustBadges: string[];
  license: string;
  withdrawalLimit: string;
  trustScoreBy: string;
  trustLabel: string;
  keyFacts: {
    founded: string;
    software: string;
    minDeposit: string;
    withdrawalTime: string;
    currencies: string;
    languages: string;
    support: string;
  };
  bonuses: Array<{
    title: string;
    bonusRequirement: string;
    withdrawRequirement: string;
    termAndCondition: string;
  }>;
  games: Array<{
    category: string;
    icon: string;
    count: string;
  }>;
  banking: {
    paymentMethods: Array<{
      name: string;
      icon: string;
    }>;
  };
  review: Array<{
    heading: string;
    content: string;
  }>;
  reviewSections: Array<{
    heading: string;
    content: string;
  }>;
}

const SHARED = {
  banner: '/welcome-banner.png',
  trustBadges: ['Licensed & Regulated', '18+ Only', 'SSL Encrypted', 'Fair Gaming', 'Responsible Gambling'],
  license: 'Curacao Gaming Authority (CGA)',
  trustScoreBy: 'Trust Score by LuckyRoo',
  trustLabel: 'Trusted by Curacao Gaming Authority (CGA)',
  keyFacts: {
    founded: '2020',
    software: 'Jili, Bng, Vpower, Rich Gaming, CQ9, Vplus, ACE333, Pragmatic Play, Joker, +50 providers',
    minDeposit: '$10 AUD',
    withdrawalTime: '24-48 hours',
    currencies: 'AUD',
    languages: 'English',
    support: '24/7 Live Chat, Email',
  },
    games: [
      { category: 'Pokies', icon: '/game-icons/slots.svg', count: '2,500+' },
      { category: 'Blackjack', icon: '/game-icons/blackjack.svg', count: '45+' },
      { category: 'Baccarat', icon: '/game-icons/baccarat.svg', count: '30+' },
      { category: 'Bingo', icon: '/game-icons/bingo.svg', count: '15+' },
      { category: 'Jackpot', icon: '/game-icons/jackpot.svg', count: '120+' },
      { category: 'Live Casino', icon: '/game-icons/live-games.svg', count: '200+' },
      { category: 'Roulette', icon: '/game-icons/roulette.svg', count: '20+' },
    ],
    banking: {
      paymentMethods: [
        { name: 'Visa', icon: '/payment-icons/visa.svg' },
        { name: 'Mastercard', icon: '/payment-icons/mastercard.svg' },
        { name: 'Bitcoin', icon: '/payment-icons/bitcoin.svg' },
        { name: 'Westpac', icon: '/payment-icons/westpac.png' },
        { name: 'NAB', icon: '/payment-icons/nab.svg' },
        { name: 'Apple Pay', icon: '/payment-icons/applepay.svg' },
        { name: 'Google Pay', icon: '/payment-icons/googlepay.svg' },
        { name: 'USDT', icon: '/payment-icons/usdt.svg' },
      ],
    },
    bonuses: [
    { title: 'Welcome Bonus', bonusRequirement: 'Get up to $5,000 + 200 Free Spins across your first 5 deposits. For new members. Minimum deposit $20 to apply.', withdrawRequirement: '35x wagering on bonus. Minimum withdrawal turnover as per site. Maximum withdrawal limits may apply.', termAndCondition: 'Register name must match bank. Cannot combine with other promotions, free credit, rebate or commission. All credit forfeited on violation of rules. T&Cs apply.' },
    { title: 'Weekly Reload', bonusRequirement: '50% match bonus up to $500 every Monday. Eligible for active members. Minimum deposit $30 to apply.', withdrawRequirement: '40x wagering. Minimum withdrawal amount as per site. Maximum may apply.', termAndCondition: 'One claim per week. Cannot combine with other promos. T&Cs apply.' },
    { title: 'Cashback', bonusRequirement: '10% cashback on losses every weekend. Credited automatically for eligible play.', withdrawRequirement: 'No wagering on cashback. Maximum withdrawal $1,000 per claim.', termAndCondition: 'Eligibility as per promotion guidelines. Cannot combine with other offers. T&Cs apply.' },
    { title: 'VIP Program', bonusRequirement: 'Earn points and climb tiers for exclusive rewards. Points on every bet.', withdrawRequirement: 'Points and rewards subject to program. Redemption terms on site.', termAndCondition: 'Points never expire. Program terms and tier benefits on official site. T&Cs apply.' },
  ],
  review: [
    { heading: 'Overview', content: 'A trusted online gaming destination offering pokies, table games, and live dealer experiences. Generous bonuses, fast withdrawals, and 24/7 support for Australian players.' },
    { heading: 'Game Selection', content: 'Wide range of pokies, blackjack, baccarat, bingo, and live casino from top providers. Mobile-optimized platform with regular new releases.' },
    { heading: 'Bonuses', content: 'Welcome package, weekly reloads, cashback, and VIP loyalty program. Wagering terms are competitive; check the site for current offers.' },
    { heading: 'Banking', content: 'Supports cards, POLi, Neosurf, and crypto. Deposits instant; withdrawals typically 24-48 hours. Minimum deposit $10.' },
    { heading: 'Final Verdict', content: 'Solid choice for Australian players: good game variety, fair bonuses, and reliable support. We recommend checking the latest promotions on the official site.' },
  ],
  reviewSections: [
    {
      heading: '{{name}} Casino Review',
      content: '{{name}} delivers a refined and reliable user experience, combining a strong game portfolio with clear licensing and player-focused terms. The site offers strong banking flexibility including bank, crypto, and digital payment methods, and operates with firmer oversight that supports confidence and credibility. This review covers the casino’s Trust Score, terms and conditions, licence and company information, payment options and withdrawal policy, and games and providers.',
    },
    {
      heading: '{{name}} Casino Trust Score',
      content: '{{name}} holds a Trust Score that reflects its licensing under the Curacao Gaming Authority (CGA), its ownership structure, and its reputation for paying players and maintaining transparent operations. The score is based on regulatory standing, banking options, game range, and the clarity of its terms. Players can use this score as one factor when deciding where to play.',
    },
    {
      heading: 'Terms & Conditions of {{name}} Casino',
      content: 'The terms and conditions of {{name}} are presented in a clear, fair, and free-from-predatory-clauses manner. The operator maintains a player-focused reputation, with key points covering bonuses, wagering, account verification, and responsible gambling. We recommend reading the full T&Cs on the official site before signing up or claiming any offer.',
    },
    {
      heading: '{{name}} Casino License & Company Information',
      content: '{{name}} is owned and operated by a licensed entity and holds a licence from the Curacao Gaming Authority (CGA). While the site does not prominently list third-party auditors or security partners, it operates within the CGA regulatory framework. For the latest company and licence details, refer to the footer or legal pages on the official {{name}} website.',
    },
    {
      heading: '{{name}} Casino Payment Options & Withdrawal Policy',
      content: '{{name}} supports an extensive range of payment methods, including major credit and debit cards, digital payment services such as Apple Pay and Google Pay, and a variety of cryptocurrencies. Withdrawals begin at a minimum threshold (e.g. A$30) with no maximum withdrawal limit for eligible payment methods. Processing times vary by method; check the cashier for current options and timeframes.',
    },
    {
      heading: '{{name}} Casino Games & Providers',
      content: '{{name}} offers a complete array of slots, table games (roulette, blackjack, baccarat), bingo, keno, scratch cards, video poker, and live dealer titles, along with support for multiple game providers. The library includes well-known studios and a broad selection of themes and mechanics. For the full list of games and providers, visit the {{name}} site directly.',
    },
  ],
};

function replaceName(str: string, name: string) {
  return str.replace(/\{\{name\}\}/g, name);
}

/** Per-casino withdrawal limit shown on the review page (e.g. sidebar "Withdrawal Limit" box). */
const WITHDRAWAL_LIMIT_BY_SLUG: Record<string, string> = {
  ipay9: 'No Limit (min. A$50)',
  kingbet9: 'No Limit (min. A$28)',
  bigpay77: 'No Limit (min. A$28)',
  me99: 'No Limit (min. A$50)',
  gucci9: 'No Limit (min. A$50)',
  rolex9: 'No Limit (min. A$29)',
  bybid9: 'No Limit (min. A$50)',
  mrbean9: 'No Limit (min. A$28)',
  pkm9: 'No Limit (min. A$28)',
  winnie777: 'No Limit (min. A$18)',
  queen13: 'No Limit (min. A$50)',
  micky9: 'No Limit (min. A$30)',
  ace96au: 'No Limit (min. A$28)',
};

/** Affiliate URLs for Read review / Play now / View bonus buttons (same destination per brand). */
const AFFILIATE_URL_BY_SLUG: Record<string, string> = {
  gucci9: 'https://gucci9office.net/RFLUCKYROOGU',
  pkm9: 'https://ppkkmmoon13.com/RFPOLUCKYROO',
  me99: 'https://me99aus.net/RFLUCKYROOME',
  mrbean9: 'https://mrbean9au.com/RFLUCKYROOMR',
  ipay9: 'https://ipay9.co/RFLUCKYROOO',
  ace96au: 'https://ace96au.com/RFLUCKYROOACE',
  rolex9: 'https://rolex9au.com/RFRLUCKYROO',
  kingbet9: 'https://king9aus.net/RFK9LUCKYROO',
  bigpay77: 'https://bigpay77aus.com/RFLLUCKYROO',
  bybid9: 'https://bybid9.net/RFLUCKYROO',
  micky9: 'https://micky13.asia/RFLUCKYROOMIC',
  queen13: 'https://queen13au.com/RFLUCKYROOQUEEN',
  winnie777: 'https://winnie777.org/RFLUCKYROOWIINE',
};

/** Per-casino overview (review) sections — same structure, different wording per brand. */
const OVERVIEW_BY_SLUG: Record<string, Array<{ heading: string; content: string }>> = {
  ipay9: [
    { heading: '{{name}} Casino Review', content: '{{name}} is a long-standing operator with a strong reputation and is one of the top-rated platforms in the Australian market. It has built trust over time through clear licensing, fair terms, and a reliable payout history. The site delivers a solid mix of pokies, table games, and live dealer games, with weekly rebates and commission offers that appeal to regular players. Minimum withdrawal is A$50; there is no maximum for eligible methods. This review covers Trust Score, terms, licence, payment options, withdrawal policy, and game range so you can decide if {{name}} is right for you.' },
    { heading: '{{name}} Casino Trust Score', content: 'The {{name}} Trust Score is based on its Curacao Gaming Authority (CGA) licensing, ownership transparency, and track record of paying players on time. It considers regulation, banking options, game variety, bonus fairness, and clarity of terms. A higher score indicates stronger reliability and player protection. Use it alongside your own preferences—such as game choice or bonus type—when choosing where to play.' },
    { heading: 'Terms & Conditions of {{name}} Casino', content: '{{name}} sets out its terms in a clear and fair way, without predatory clauses. Key areas include bonus eligibility, wagering requirements, account verification, withdrawal rules, and responsible gambling tools. The operator is known for player-focused policies; we still recommend reading the full T&Cs on the official site before signing up or claiming any offer, so you know exactly what applies to your play.' },
    { heading: '{{name}} Casino License & Company Information', content: '{{name}} is operated by a licensed entity under the Curacao Gaming Authority (CGA). The licence ensures the operator meets baseline standards for fairness and security. For up-to-date company name, jurisdiction, and licence details, always check the footer and legal pages on the official {{name}} website, as this information can change.' },
    { heading: '{{name}} Casino Payment Options & Withdrawal Policy', content: '{{name}} supports cards, e-wallets, and selected cryptocurrencies. Deposits are typically instant; withdrawals have a minimum of A$50 and no maximum for eligible methods, which suits both casual and high-roller players. Processing times depend on the method and verification status; first-time withdrawals may take longer. See the cashier on the official site for current options, limits, and timeframes.' },
    { heading: '{{name}} Casino Games & Providers', content: '{{name}} provides a broad range of slots, table games, bingo, and live dealer titles from multiple providers. The library is regularly updated with new releases, and many games are available on mobile. Slot welcome bonuses, weekly rebates, and commission offers are tied to specific products as set out in the bonus terms. For the full list of games and studios, visit the {{name}} site.' },
  ],
  kingbet9: [
    { heading: '{{name}} Casino Review', content: '{{name}} positions itself as a prestige, reputable, and royal-style brand for the Australian market. It offers a strong game selection, competitive welcome and daily bonuses, and crypto-friendly banking. Minimum withdrawal is A$28, which is lower than many competitors and convenient for smaller cashouts. The site combines clear licensing with flexible payment options and is available on app for iOS and Android. This review outlines Trust Score, terms, licence, banking, and games.' },
    { heading: '{{name}} Casino Trust Score', content: '{{name}}\'s Trust Score reflects its Curacao Gaming Authority (CGA) licence, ownership structure, and reputation for timely payouts and transparency. We factor in regulation, payment variety (including crypto), game range, and the clarity of bonus and withdrawal terms. Consider this score alongside your own priorities—such as game type or minimum withdrawal—when comparing casinos.' },
    { heading: 'Terms & Conditions of {{name}} Casino', content: '{{name}} presents terms that are readable and balanced, with clear sections on bonuses, wagering, account verification, and responsible gaming. Slot and daily bonus rollover requirements are stated in the bonus terms. We recommend reviewing the full T&Cs on the operator\'s site before registering or claiming any offer, so you understand eligibility and withdrawal conditions.' },
    { heading: '{{name}} Casino License & Company Information', content: '{{name}} is run by an operator licensed under the Curacao Gaming Authority (CGA). The licence indicates that the operator is subject to regulatory oversight. For the latest company name, registered address, and licence number, refer to the official {{name}} site\'s legal or footer sections.' },
    { heading: '{{name}} Casino Payment Options & Withdrawal Policy', content: '{{name}} accepts cards, e-wallets, and several cryptocurrencies. Withdrawals start at a minimum of A$28 with no cap for eligible methods. Processing times vary by method and verification; crypto and e-wallets are often faster. Check the cashier on the official site for current methods, minimums, and typical timeframes.' },
    { heading: '{{name}} Casino Games & Providers', content: '{{name}} features slots, blackjack, baccarat, bingo, and live dealer games from well-known providers. The catalogue is updated regularly, and many titles are playable on the KingBet9 app. Bonus eligibility (e.g. slot-only) is described in each promotion. Visit the {{name}} site for the complete game and provider list.' },
  ],
  bigpay77: [
    { heading: '{{name}} Casino Review', content: '{{name}} stands out with plenty of platform benefits, a large game library, and a smooth gaming experience with no noticeable delay—important for slots and live play. It supports iOS and Android via dedicated app and APK, so you can play on the go with the same quality. The casino has no withdrawal cap for eligible methods, generous welcome and deposit bonuses, and transparent banking and licensing. Here we cover Trust Score, terms, licence, payments, and game offering in detail.' },
    { heading: '{{name}} Casino Trust Score', content: 'The Trust Score for {{name}} reflects its CGA licensing, ownership transparency, and its standing for paying players fairly and on time. We consider regulation, banking options (including no max withdrawal), game diversity, and the clarity of bonus and withdrawal terms. Use it as one factor in your decision, together with your preference for app play and game variety.' },
    { heading: 'Terms & Conditions of {{name}} Casino', content: '{{name}} keeps its T&Cs clear and fair, with no predatory wording. Key areas include bonus eligibility (e.g. slot vs. live), wagering and rollover, verification steps, and responsible gambling. Weekend and daily bonus terms are set out per promotion. Read the full terms on the official site before signing up or claiming any bonus.' },
    { heading: '{{name}} Casino License & Company Information', content: '{{name}} operates under a Curacao Gaming Authority (CGA) licence, which provides a baseline level of regulatory oversight. For current company name, jurisdiction, and licence details—which can change—see the official {{name}} website\'s legal or footer pages.' },
    { heading: '{{name}} Casino Payment Options & Withdrawal Policy', content: '{{name}} offers multiple payment methods including cards, e-wallets, and crypto. There is no maximum withdrawal for eligible options, which is a plus for big winners; minimum withdrawal is A$28. Processing times vary by method and verification; see the cashier for current methods, minimums, and typical timeframes.' },
    { heading: '{{name}} Casino Games & Providers', content: '{{name}} offers a full suite of slots, table games, bingo, and live dealer titles from various providers. Games run smoothly on both desktop and the iOS/Android app. Bonus terms specify which games qualify (e.g. slots only). For the complete list of games and studios, head to the {{name}} site.' },
  ],
  me99: [
    { heading: '{{name}} Casino Review', content: '{{name}} is a reputable operator known for a wide range of bonuses—including daily rebates, every-deposit random bonuses, slot welcome offers, and daily free credits. It appeals to both fiat and crypto users and offers live dealer games plus a solid slot and table library. The platform is easy to use, licensed, and suitable for players who like to claim bonuses frequently. This review covers Trust Score, terms, licence, banking, and games.' },
    { heading: '{{name}} Casino Trust Score', content: '{{name}}\'s Trust Score is derived from its Curacao Gaming Authority (CGA) licence, ownership details, and reputation for fair and timely payouts. We factor in regulation, banking (fiat and crypto), game range, and the transparency of bonus and rebate terms. Players can use it when comparing sites, especially if bonus variety and reliability matter to you.' },
    { heading: 'Terms & Conditions of {{name}} Casino', content: 'Terms at {{name}} are set out in a clear and fair manner. They cover bonus eligibility, rebate and rollover rules, verification, and responsible gambling. Some offers are wallet-balance dependent or slot-only. We advise reading the full T&Cs on the official {{name}} site before registering or claiming any promotion.' },
    { heading: '{{name}} Casino License & Company Information', content: '{{name}} is owned and operated under a Curacao Gaming Authority (CGA) licence. This provides a standard level of regulatory oversight for fairness and dispute handling. For the latest company name and licence information, consult the official {{name}} website\'s legal or footer section.' },
    { heading: '{{name}} Casino Payment Options & Withdrawal Policy', content: '{{name}} supports both fiat and crypto for deposits and withdrawals. Minimum withdrawal is A$50; processing times vary. First-time withdrawals can take longer due to verification. Check the cashier for current options and typical timeframes.' },
    { heading: '{{name}} Casino Games & Providers', content: '{{name}} provides slots, table games, and live dealer titles from a selection of providers. Many bonuses are valid on slots or selected products as per each promotion. For the full game and provider list, visit the {{name}} site.' },
  ],
  rolex9: [
    { heading: '{{name}} Casino Review', content: '{{name}} aims for a premium experience with plenty of event rewards and promotions—including weekly rebates, slot welcome bonuses, free credits, and random withdraw bonuses. The site offers a wide game range, daily and weekly rewards, and reliable support. Licensing and banking are clear, and the brand appeals to players who like regular promotions. This review explains Trust Score, terms, licence, payments, and games.' },
    { heading: '{{name}} Casino Trust Score', content: 'The {{name}} Trust Score reflects its CGA licensing, ownership structure, and its record on payouts and transparency. We consider regulation, banking options, game variety, and the clarity of bonus and rebate terms. Consider it when choosing a casino, especially if you value event-style offers and consistent promotions.' },
    { heading: 'Terms & Conditions of {{name}} Casino', content: '{{name}} presents fair and readable terms covering bonuses, wagering, verification, and responsible gaming. Some promotions have wallet-balance conditions or are slot-only. Always read the full T&Cs on the official site before signing up or claiming any offer, so you know rollover and eligibility.' },
    { heading: '{{name}} Casino License & Company Information', content: '{{name}} is run by an entity licensed by the Curacao Gaming Authority (CGA). The licence indicates regulatory oversight for fairness and security. For up-to-date company and licence details, see the official {{name}} website\'s legal or footer section.' },
    { heading: '{{name}} Casino Payment Options & Withdrawal Policy', content: '{{name}} supports cards, e-wallets, and crypto with generally fast processing for verified accounts. Minimum withdrawal is A$29; no maximum for eligible methods. See the cashier for current options and typical processing times.' },
    { heading: '{{name}} Casino Games & Providers', content: '{{name}} offers a wide range of pokies, table games, and live dealer from multiple providers. Bonus eligibility (e.g. slot welcome, rebate on selected games) is set out in each promotion. For the complete catalogue, visit the {{name}} site.' },
  ],
  gucci9: [
    { heading: '{{name}} Casino Review', content: '{{name}} delivers a premium themed experience with plenty of platform benefits, a large game library, and a smooth gaming experience with no noticeable delay. It supports iOS and Android via app and APK, so you get the same quality on mobile. The site is fully licensed with multiple payment options—including Australian-friendly methods—and clear terms. Weekly commission, daily free steps, and slot welcome bonuses are among the key offers. This review covers Trust Score, T&Cs, licence, banking, and games.' },
    { heading: '{{name}} Casino Trust Score', content: '{{name}}\'s Trust Score is based on Curacao Gaming Authority (CGA) licensing, ownership transparency, and reputation for paying players. We include regulation, banking options, game range, and the clarity of bonus and commission terms. Use it as one factor in your choice, especially if you value theme, app support, and bonus variety.' },
    { heading: 'Terms & Conditions of {{name}} Casino', content: '{{name}} maintains clear and fair terms with emphasis on bonuses, wagering, verification, and responsible gambling. Commission and rebate offers may have wallet or product restrictions. Read the full T&Cs on the official {{name}} site before registering or claiming any bonus.' },
    { heading: '{{name}} Casino License & Company Information', content: '{{name}} operates under a Curacao Gaming Authority (CGA) licence. For current company name, jurisdiction, and licence information—which can change—refer to the official {{name}} website\'s legal or footer pages.' },
    { heading: '{{name}} Casino Payment Options & Withdrawal Policy', content: '{{name}} accepts cards, e-wallets, and crypto. Minimum withdrawal is A$50; eligible methods may have no maximum. Processing times vary by method and verification; check the cashier for current options and typical timeframes.' },
    { heading: '{{name}} Casino Games & Providers', content: '{{name}} features slots, table games, and live dealer from reputable providers. Many promotions are valid on selected slot brands (e.g. 918Kaya, Joker, CQ9). For the full list of games and studios, visit the {{name}} site.' },
  ],
  pkm9: [
    { heading: '{{name}} Casino Review', content: '{{name}} brings a Pokémon-themed experience that is new-player friendly and user-focused. It offers popular game brands, a mobile-friendly platform, and regular new releases and promotions—including slot welcome, every-deposit random bonus, daily free credit, and daily slot bonus. Licensing and terms are straightforward, and the theme makes the site easy and fun to navigate. This review covers Trust Score, terms, licence, banking, and games.' },
    { heading: '{{name}} Casino Trust Score', content: 'The Trust Score for {{name}} reflects its CGA licence, ownership structure, and standing for fair payouts. We consider regulation, banking, game variety, and the transparency of bonus terms. Players can use it when comparing options, especially if you care about theme, new-player experience, and bonus variety.' },
    { heading: 'Terms & Conditions of {{name}} Casino', content: '{{name}} sets out terms in a clear way, covering bonuses, wagering, verification, and responsible gambling. Some offers are slot-only or require social steps. We recommend reading the full T&Cs on the official site before signing up or claiming any promotion.' },
    { heading: '{{name}} Casino License & Company Information', content: '{{name}} is operated by a company licensed by the Curacao Gaming Authority (CGA). For the latest company name and licence details, see the official {{name}} website\'s legal or footer section.' },
    { heading: '{{name}} Casino Payment Options & Withdrawal Policy', content: '{{name}} supports a range of payment methods. Minimum withdrawal is A$28; processing times depend on the method and verification. Check the cashier for current options and typical timeframes.' },
    { heading: '{{name}} Casino Games & Providers', content: '{{name}} offers a good mix of pokies and table games from well-known providers, with regular new titles. Bonus eligibility (e.g. designated slots, WF2) is described in each offer. For the full catalogue, visit the {{name}} site.' },
  ],
  mrbean9: [
    { heading: '{{name}} Casino Review', content: '{{name}} features a Mr. Bean–themed design that is fun and recognisable. The site is customer-focused, offers plenty of bonuses—including daily easy step, Monday slot bonus, every-deposit random, and daily first deposit—and is easy to get started with. Gameplay is smooth and event rewards are frequent. With quick payouts and a solid selection of pokies and table games, it suits players who like a light-hearted theme and regular promotions. This review outlines Trust Score, terms, licence, banking, and games.' },
    { heading: '{{name}} Casino Trust Score', content: '{{name}}\'s Trust Score is derived from CGA licensing, ownership transparency, and its reputation for paying players. We factor in regulation, banking, game range, and the clarity of bonus and withdrawal terms. Consider it when deciding where to play, especially if you value theme, ease of use, and bonus variety.' },
    { heading: 'Terms & Conditions of {{name}} Casino', content: '{{name}} provides readable and fair terms covering bonuses, wagering, verification, and responsible gaming. Some promotions require social sharing or are slot-only. Always read the full T&Cs on the official site before registering or claiming any offer.' },
    { heading: '{{name}} Casino License & Company Information', content: '{{name}} is run under a Curacao Gaming Authority (CGA) licence. For current company and licence information, consult the official {{name}} website\'s legal or footer section.' },
    { heading: '{{name}} Casino Payment Options & Withdrawal Policy', content: '{{name}} offers several payment options with quick processing for verified accounts. Minimum withdrawal is A$28; see the cashier for current options and typical timeframes.' },
    { heading: '{{name}} Casino Games & Providers', content: '{{name}} has a solid selection of pokies and table games from a range of providers. Bonus terms specify eligible products (e.g. WF2, slots). For the complete list, visit the {{name}} site.' },
  ],
  micky9: [
    { heading: '{{name}} Casino Review', content: '{{name}} brings a Mickey-themed experience and is customer-focused with a wide range of bonuses—including weekly rebate, weekly commission, 365 random daily free, and free credit offers. It is licensed by the Curacao Gaming Authority (CGA) and supports leading Australian banks plus a wide game selection. The operator is transparent and Australia-focused, and the theme makes the site approachable. This review covers Trust Score, terms, licence, banking, and games.' },
    { heading: '{{name}} Casino Trust Score', content: 'The {{name}} Trust Score reflects its CGA licence, ownership structure, and reputation for fair and timely payouts. We consider regulation, banking (including Australian options), game variety, and the clarity of bonus and rebate terms. Use it when comparing casinos, especially if you value theme, Australian payment support, and bonus variety.' },
    { heading: 'Terms & Conditions of {{name}} Casino', content: '{{name}} maintains clear and fair terms with focus on bonuses, wagering, verification, and responsible gambling. Rebate and free-credit offers have specific game and rollover rules. Read the full T&Cs on the official {{name}} site before signing up or claiming any bonus.' },
    { heading: '{{name}} Casino License & Company Information', content: '{{name}} is licensed by the Curacao Gaming Authority (CGA). For the latest company name and licence details, refer to the official {{name}} website\'s legal or footer section.' },
    { heading: '{{name}} Casino Payment Options & Withdrawal Policy', content: '{{name}} supports Australian banks, cards, e-wallets, and crypto. Minimum withdrawal is A$30; processing times vary by method and verification. Check the cashier for current options and typical timeframes.' },
    { heading: '{{name}} Casino Games & Providers', content: '{{name}} offers a wide range of slots, table games, and live dealer from multiple providers. Many bonuses apply to selected slot brands (e.g. 918Kaya, Joker, CQ9). For the full list, visit the {{name}} site.' },
  ],
  winnie777: [
    { heading: '{{name}} Casino Review', content: '{{name}} offers a Winnie-the-Pooh themed experience that is easy to get started with and delivers smooth gameplay plus plenty of event rewards. It stands out with generous bonuses—weekly rebate, every-deposit random, free credit, and 365 daily free—along with 24/7 support and a large library of pokies and live games. Banking and licensing are clear, and there is no maximum withdrawal for eligible methods. This review covers Trust Score, terms, licence, payments, and games.' },
    { heading: '{{name}} Casino Trust Score', content: '{{name}}\'s Trust Score is based on CGA licensing, ownership transparency, and its record of paying players. We include regulation, banking options, game range, and the clarity of bonus and rebate terms. Use it as one factor when choosing a casino, especially if you like the theme, ease of use, and frequent promotions.' },
    { heading: 'Terms & Conditions of {{name}} Casino', content: '{{name}} presents terms in a clear and fair manner, covering bonuses, wagering, verification, and responsible gambling. Some offers have wallet-balance conditions or apply to selected games only. We recommend reading the full T&Cs on the official site before registering or claiming any offer.' },
    { heading: '{{name}} Casino License & Company Information', content: '{{name}} operates under a Curacao Gaming Authority (CGA) licence. For up-to-date company and licence information, see the official {{name}} website\'s legal or footer section.' },
    { heading: '{{name}} Casino Payment Options & Withdrawal Policy', content: '{{name}} supports multiple methods including crypto; no maximum withdrawal for eligible options. Minimum withdrawal is A$18; processing times vary by method and verification. See the cashier for current options and typical timeframes.' },
    { heading: '{{name}} Casino Games & Providers', content: '{{name}} provides a large library of pokies and live dealer games from top providers. Bonus terms specify eligible products (e.g. WF Gaming, AFB777, EVO888H5). For the complete catalogue, visit the {{name}} site.' },
  ],
  bybid9: [
    { heading: '{{name}} Casino Review', content: '{{name}} is new-player friendly with plenty of jackpot rewards—including premium jackpot offers and daily and social free bonuses. The brand emphasises fast 24-hour service, customer focus, security and trust, innovation, an efficient team, 24/7 support, transparent and fair terms, a user-friendly platform, high-quality service, and a top jackpot bonus. The casino has no withdrawal cap and transparent terms and banking. This review outlines Trust Score, terms, licence, banking, and games so you can see how {{name}} compares.' },
    { heading: '{{name}} Casino Trust Score', content: 'The Trust Score for {{name}} reflects its CGA licence, ownership structure, and reputation for fair payouts. We consider regulation, banking (including no max withdrawal), game range, and the transparency of bonus and jackpot terms. Consider it when comparing sites, especially if you value new-player offers and jackpot-style rewards.' },
    { heading: 'Terms & Conditions of {{name}} Casino', content: '{{name}} keeps terms clear and fair, with emphasis on bonuses, wagering, verification, and responsible gambling. Some promotions are event-game or app-only. Always read the full T&Cs on the official {{name}} site before signing up or claiming any offer.' },
    { heading: '{{name}} Casino License & Company Information', content: '{{name}} is run by an entity licensed by the Curacao Gaming Authority (CGA). For current company name and licence details, refer to the official {{name}} website\'s legal or footer section.' },
    { heading: '{{name}} Casino Payment Options & Withdrawal Policy', content: '{{name}} has no maximum withdrawal for eligible methods; minimum withdrawal is A$50. Multiple banking and crypto options are available. Check the cashier for current methods and typical processing times.' },
    { heading: '{{name}} Casino Games & Providers', content: '{{name}} features slots, table games, bingo, and live dealer from various providers. Many bonuses apply to event or slot products as per each promotion. For the full list, visit the {{name}} site.' },
  ],
  queen13: [
    { heading: '{{name}} Casino Review', content: '{{name}} stands out with strong new-member registration rewards (e.g. New Member Free AUD 113, Telegram task free), good rebates such as the weekly rebate bonus, fast withdrawals, and excellent customer support. The site displays plenty of event and promotional benefits and combines premium design with a solid mix of bonuses and games. Licensing and terms are clear. This review covers Trust Score, T&Cs, licence, banking, and game offering.' },
    { heading: '{{name}} Casino Trust Score', content: '{{name}}\'s Trust Score is derived from CGA licensing, ownership transparency, and its reputation for paying players. We factor in regulation, banking, game variety, and the clarity of bonus and rebate terms. Players can use it when deciding where to play, especially if you value new-member offers, rebates, and support quality.' },
    { heading: 'Terms & Conditions of {{name}} Casino', content: '{{name}} sets out fair and readable terms covering bonuses, wagering, verification, and responsible gambling. Some offers are event- or app-only and have specific task requirements. Read the full T&Cs on the official site before registering or claiming any offer.' },
    { heading: '{{name}} Casino License & Company Information', content: '{{name}} is operated under a Curacao Gaming Authority (CGA) licence. For the latest company and licence information, see the official {{name}} website\'s legal or footer section.' },
    { heading: '{{name}} Casino Payment Options & Withdrawal Policy', content: '{{name}} supports secure payments with transparent policies. Minimum withdrawal is A$50; processing times vary by method. Fast withdrawal is a stated strength of the brand. See the cashier for current options and timeframes.' },
    { heading: '{{name}} Casino Games & Providers', content: '{{name}} offers a solid game selection from reputable providers. Many promotions apply to event or slot products as per each offer. For the complete list of games and studios, visit the {{name}} site.' },
  ],
  ace96au: [
    { heading: '{{name}} Casino Review', content: '{{name}} is a newly launched Australian tech entertainment platform with limited-time rewards, strong new-member offers (e.g. VVIP bonus, referral bonus), and plenty of deposit bonuses including weekly commission and special rebate. Gameplay is smooth, withdrawals are fast, and customer support is excellent. The site focuses on Australian players with local payment options and fair terms. This review covers Trust Score, terms, licence, banking, and games.' },
    { heading: '{{name}} Casino Trust Score', content: 'The {{name}} Trust Score reflects its CGA licence, ownership structure, and reputation for reliability as a new entrant. We consider regulation, Australian-friendly banking, game range, and the clarity of bonus and withdrawal terms. Use it as a factor when choosing a casino, especially if you value new platforms, deposit bonuses, and support.' },
    { heading: 'Terms & Conditions of {{name}} Casino', content: '{{name}} presents clear and fair terms covering bonuses, wagering, verification, and responsible gambling. Some offers are once-per-member or slot-only. We recommend reading the full T&Cs on the official {{name}} site before signing up or claiming any bonus.' },
    { heading: '{{name}} Casino License & Company Information', content: '{{name}} is licensed under the Curacao Gaming Authority (CGA). As a newly launched brand, licence and company details are important to verify. For current information, refer to the official {{name}} website\'s legal or footer section.' },
    { heading: '{{name}} Casino Payment Options & Withdrawal Policy', content: '{{name}} supports Australian banks and popular e-wallets. Minimum withdrawal is A$28; the brand highlights fast withdrawal. Check the cashier for current options and typical processing times.' },
    { heading: '{{name}} Casino Games & Providers', content: '{{name}} provides a good range of games suited to Australian players. Bonus terms specify eligible products (e.g. slot, event). For the full catalogue of games and providers, visit the {{name}} site.' },
  ],
};

/** Per-casino bonus offers — each brand has its own titles, descriptions, and terms. */
const BONUSES_BY_SLUG: Record<string, Array<{ title: string; bonusRequirement: string; withdrawRequirement: string; termAndCondition: string }>> = {
  ipay9: [
    { title: 'Welcome Bonus 50%', bonusRequirement: 'For new members only. Minimum deposit AUD 30 to apply. Maximum bonus up to AUD 250. Valid on all slot games; not on live or fishing games.', withdrawRequirement: 'Slot Welcome Bonus Rollover x6. Minimum withdraw turnover x6, maximum x100.', termAndCondition: 'Register name must be same as bank. All promotion cannot combined other promotion, free credit, rebate & commission. All credit will be forfeited subject to any violation of rules.' },
    { title: 'Weekly Bonus 5%', bonusRequirement: '5% rebate will be automatically issued every Monday (00:00:00 AM till 00:15:00 AM) to eligible iPay9 members. The amount of the daily rebate is based on the total deposit minus total withdrawal in the day (00:00:00 AM till 23:59:59). Can play on all games/product. Save free game excluded.', withdrawRequirement: 'Rebate rollover x3. Minimum withdraw AUD 50. Maximum withdraw AUD 599.', termAndCondition: 'Register name must be same as bank. Only can apply when wallet is below AUD 1. All promotion cannot combined other promotion, free credit, rebate & commission. All credit will be forfeited subject to any violation of rules.' },
    { title: 'Weekly Commission 7%', bonusRequirement: '7% weekly commission will be automatically issued every Monday (12:00:00 PM) to eligible iPay9 members. The amount is based on the total deposit minus total withdrawal of your all downline between this week. Valid product: only for selected slot game. Save free game excluded.', withdrawRequirement: 'Commission rollover x10. Minimum withdraw AUD 50. Maximum withdraw AUD 599.', termAndCondition: 'Register name must be same as bank. Only can apply when wallet is below AUD 1. All promotion cannot combined other promotion, free credit, rebate & commission. All credit will be forfeited subject to any violation of rules.' },
    { title: 'Free Credit 100', bonusRequirement: 'AUD 100 can be claimed once (1) daily (reset at 12:00 AM). Eligible for all iPay9 members. Complete all the steps given by customer service. Members must share your own referral link to 5 different Facebook groups chat. Remark: after share, kindly screenshot and send to livechat for verify. Valid product: selected games only (slot game only). Only claim in iPay9 APP. Save free game excluded. Other slot product, live casino and fish game excluded.', withdrawRequirement: 'Credit must hit over AUD 1000 to unlock withdraw. Maximum withdraw amount AUD 20.', termAndCondition: 'Register name must be same as bank. Only can apply when wallet is below AUD 1. All promotion cannot combined other promotion, free credit, rebate & commission. All credit will be forfeited subject to any violation of rules.' },
  ],
  kingbet9: [
    { title: 'Slot Welcome Bonus 100%', bonusRequirement: 'For new member claim once (1) only. Minimum deposit AUD 50 to apply this promotion. Maximum bonus up to AUD 500. Can play on all slot games/product. Live game and fishing game excluded. Save free game excluded.', withdrawRequirement: '(Slot Welcome Bonus Rollover x 10). Minimum withdraw turnover x 6. Maximum withdraw turnover x 100.', termAndCondition: 'Register name must be same as bank. All promotion cannot combined other promotion, free credit, rebate & commission. All credit will be forfeited subject to any violation of rules.' },
    { title: 'Slot Daily Bonus 39%', bonusRequirement: 'KingBet9 member can claim once (1) everyday. Minimum deposit AUD 50 to apply this promotion. Maximum bonus up to AUD 60. Can play on all slot games/product. Live game and fishing game excluded. Save free game excluded.', withdrawRequirement: '(Slot Daily Bonus Rollover x 4). Minimum withdraw turnover x 3. Maximum withdraw turnover x 100.', termAndCondition: 'Register name must be same as bank. All promotion cannot combined other promotion, free credit, rebate & commission. All credit will be forfeited subject to any violation of rules.' },
    { title: 'Unlimited Random Bonus', bonusRequirement: 'KingBet9 member claim unlimited time everyday. Minimum deposit AUD 10 to apply this promotion. Can play on all slot games/product. Live game and fishing game excluded. Save free game excluded.', withdrawRequirement: '(Slot Unlimited Bonus Rollover x 1.5). Random bonus will get amount AUD 0.10 – AUD 5.00. Minimum withdraw AUD 50. Maximum withdraw amount AUD 50000.', termAndCondition: 'Register name must be same as bank. All promotion cannot combined other promotion, free credit, rebate & commission. All credit will be forfeited subject to any violation of rules.' },
    { title: 'Daily Easy Step Free A$100', bonusRequirement: 'Complete all the step that giving by customer service. Contact us for more information. Live Chat: https://kingbet9auss.com/chatroom. Share bonus term & condition. Valid product: MEGA888H52, RG2, EPICWIN2, WF2. Only claim in KingBet9 APP. Save free game excluded. Other slot product, live game and fishing game excluded.', withdrawRequirement: 'Credit must hit over 1,000.00 to unlock withdraw. Maximum withdraw AUD 20.', termAndCondition: 'Register name must be same as bank. Only can apply when wallet is below AUD 1. All promotion cannot combined other promotion, free credit, deposit, rebate & commission. All credit will be forfeited subject to any violation of rules.' },
  ],
  bigpay77: [
    { title: 'Welcome Bonus 80%', bonusRequirement: 'For new member claim once (1) only. Minimum deposit AUD 50 to apply this promotion. Maximum bonus up to AUD 250. Can play on all slot games/product. Live game and fishing game excluded. Save free game excluded.', withdrawRequirement: '(Slot Welcome Bonus Rollover x 6). Minimum withdraw turnover x 6. Maximum withdraw amount AUD 50000.', termAndCondition: 'Register name must be same as bank. All promotion cannot combined other promotion, free credit, rebate & commission. All credit will be forfeited subject to any violation of rules.' },
    { title: 'Deposit Random Bonus', bonusRequirement: 'BIGPAY77 member claim unlimited time everyday. Minimum deposit AUD 20 to apply this promotion. Can play on all slot games/product. Live game and fishing game excluded. Save free game excluded.', withdrawRequirement: '(Slot Unlimited Bonus Rollover x 1.5). Random bonus will get amount AUD 0.10 – AUD 5.00. Minimum withdraw AUD 50. Maximum withdraw amount AUD 50000.', termAndCondition: 'Register name must be same as bank. All promotion cannot combined other promotion, free credit, rebate & commission. All credit will be forfeited subject to any violation of rules.' },
    { title: 'Weekend Deposit 30%', bonusRequirement: 'Member can claim once (1) weekly. Minimum deposit AUD 50 to apply this promotion. Maximum bonus up to AUD 288. Can play on all slot games/product. Live game and fishing game excluded. Save free game excluded.', withdrawRequirement: '(Slot Daily Bonus Rollover x 4). Minimum withdraw turnover x 3. Maximum withdraw turnover x 100.', termAndCondition: 'Register name must be same as bank. All promotion cannot combined other promotion, free credit, rebate & commission. All credit will be forfeited subject to any violation of rules.' },
    { title: 'Daily Easy Step Free $100', bonusRequirement: 'Complete all the step that giving by customer service. Contact us for more information. Live Chat: https://bigpay77.net/chatroom. Share bonus term & condition. All BIGPAY77 customer can claim this bonus everyday. Members are required to share their unique referral link in at least 5 different Facebook group chats. Shares to the same group will not be considered valid. Shares that are removed will not be counted. Remark: after sharing, please take a screenshot and send it to livechat for verification. Valid product: only MegaH52 & certain games only. Only claim in BIGPAY77 APP. Save free game excluded. Other slot product, live game and fishing game excluded.', withdrawRequirement: 'Credit must hit over 1,000.00 to unlock withdraw. Maximum withdraw AUD 20.', termAndCondition: 'Register name must be same as bank. Only can apply when wallet is below AUD 1. All promotion cannot combined other promotion, free credit, rebate & commission. All credit will be forfeited subject to any violation of rules.' },
  ],
  me99: [
    { title: 'Rebate Bonus 5%', bonusRequirement: '5% rebate automatically issued daily (00:00:00 AM until 00:15:00 AM) to eligible Me99 members. Daily rebate is calculated based on (Total Deposit minus Total Withdrawal) from 00:00:00 AM until 23:59:59. Example: deposit $1000, withdraw $100 (lose $900) = $900 × 5% = $45 rebate; if you win (e.g. withdraw more than deposit), no rebate for that day. Can play on all games/product. Save free game excluded.', withdrawRequirement: 'Rebate rollover x3. Minimum withdraw AUD 30. Maximum withdraw AUD 599.', termAndCondition: 'Register name must be same as bank. Promotion can only be applied when wallet balance is below AUD 1. This promotion cannot be combined with any other promotion, free credit, deposit bonus, rebate or commission. All credit will be forfeited subject to any violation of rules.' },
    { title: 'Every Deposit Random Bonus', bonusRequirement: 'Me99 members can claim unlimited times every day. Minimum deposit AUD 20 to apply this promotion. Can play on all slot games/product. Live game and fishing game excluded. Save free game excluded.', withdrawRequirement: 'Slot unlimited bonus rollover x 1.5. Random bonus will get amount AUD 0.10 – AUD 5.00. Minimum withdraw AUD 50. Maximum withdraw amount AUD 50000.', termAndCondition: 'Register name must be same as bank. All promotion cannot combined other promotion, free credit, rebate & commission. All credit will be forfeited subject to any violation of rules.' },
    { title: 'Slot Welcome Bonus 50%', bonusRequirement: 'For new members, claim once (1) only. Minimum deposit AUD 50 to apply this promotion. Maximum bonus up to AUD 250. Can play on all slot games/product. Live game and fishing game excluded. Save free game excluded.', withdrawRequirement: 'Slot Welcome Bonus rollover x 6. Minimum withdraw turnover x 6. Maximum withdraw turnover x 100.', termAndCondition: 'Register name must be same as bank. All promotion cannot combined other promotion, free credit, rebate & commission. All credit will be forfeited subject to any violation of rules.' },
    { title: 'Daily Easy Step Free $100', bonusRequirement: 'All ME99 customers can claim this bonus one time every day. Members are required to share their unique referral link in at least 5 different Facebook group chats. Shares to the same group will not be considered valid. Shares that are removed will not be counted. Remark: After sharing, please take a screenshot and send it to livechat for verification. Can play on WF2 these games/product. Live game and fishing game excluded. Save free game excluded.', withdrawRequirement: 'Credit must hit over AUD 1000 to unlock withdraw. Maximum withdraw AUD 20.', termAndCondition: 'Register name must be same as bank. All promotion cannot combined other promotion, free credit, rebate & commission. All credit will be forfeited subject to any violation of rules.' },
  ],
  rolex9: [
    { title: 'Slot Welcome Bonus 50%', bonusRequirement: 'For new member claim once (1) only. Minimum deposit AUD 10 to apply this promotion. Maximum bonus up to AUD 250. Can play on all slot games/product. Live game and fishing game excluded. Save free game excluded.', withdrawRequirement: '(Slot Welcome Bonus Rollover x 6). Minimum withdraw turnover x 6. Maximum withdraw turnover x 100.', termAndCondition: 'Register name must be same as bank. Only can apply when wallet is below AUD 1. All promotion cannot combined other promotion, free credit, rebate & commission. All credit will be forfeited subject to any violation of rules.' },
    { title: 'Free Credit 99.99', bonusRequirement: 'Free bonus of AUD 99.99. Limited to 1 claim per month. Complete all the steps instructed by our customer service. Contact us for more information. Live Chat: https://rolex9au.com/chatroom. Share bonus term & condition. Valid: EVO888H5B only. Save free game, other slot product, live game and fishing game excluded.', withdrawRequirement: 'Credit must hit over 999.99 to unlock withdraw. Maximum withdraw AUD 20.', termAndCondition: 'Register name must be same as bank. Only can apply when wallet is below AUD 1. All promotion cannot combined other promotion, free credit, deposit, rebate & commission. All credit will be forfeited subject to any violation of rules.' },
    { title: 'Random Second Withdraw Bonus', bonusRequirement: 'Min deposit as low as 19 AUD to join. Require minimum deposit 19 AUD or higher to have chance to get this bonus. This bonus is selected by system randomly. When you are selected by system our live chat agent will contact you. Only deposit 19 AUD required to join this event. Can play on all games/product. Save free game excluded.', withdrawRequirement: 'When selected by system, enjoy the double of withdraw. Withdrawal terms as notified by live chat agent.', termAndCondition: 'Register name must be same as bank. Only can apply when wallet is below AUD 1. All promotion cannot combined other promotion, free credit, deposit, rebate & commission. All credit will be forfeited subject to any violation of rules.' },
    { title: 'Weekly Rebate 7%', bonusRequirement: '7% rebate will be automatically issued every Monday to eligible Rolex9 members. The amount of the weekly rebate is based on the total deposit minus total withdrawal in this week. Example: total deposit $1000 − total withdrawal $100 = lose $900 x 7% = rebate $63. Win for the week = no rebate. Can play on all games/product. Save free game excluded.', withdrawRequirement: '(Rebate rollover x 3). Minimum withdraw AUD 50. Maximum withdraw AUD 999.', termAndCondition: 'Register name must be same as bank. Only can apply when wallet is below AUD 1. All promotion cannot combined other promotion, free credit, rebate & commission. All credit will be forfeited subject to any violation of rules.' },
  ],
  gucci9: [
    { title: 'Weekly Commission 5%', bonusRequirement: '5% commission automatically issued every Monday at 12:00:00 PM to eligible Gucci9 members. Amount calculated on total deposit minus total withdrawal of your all downline between this week. Valid on selected slot games/product (e.g. 918KAYA, JOKER, ACE333, CQ9, Jili, Pegasus and others as per site). Save free game excluded.', withdrawRequirement: 'Commission rollover x10. Minimum withdraw AUD 50. Maximum withdraw AUD 599.', termAndCondition: 'Register name must be same as bank. Only can apply when wallet balance is below AUD 1. This promotion cannot be combined with any other promotion, free credit, rebate or commission. All credit will be forfeited subject to any violation of rules.' },
    { title: 'Daily Easy Step Free $100', bonusRequirement: 'All Gucci9 customers can claim this bonus every day. Members are required to share their unique referral link in at least 5 different Facebook group chats. Shares to the same group will not be considered valid. Shares that are removed will not be counted. Remark: After sharing, please take a screenshot and send it to livechat for verification. Can play on WF2 these games/product. Live game and fishing game excluded. Save free game excluded.', withdrawRequirement: 'Credit must hit over AUD 1000 to unlock withdraw. Maximum withdraw AUD 20.', termAndCondition: 'Register name must be same as bank. All promotion cannot combined other promotion, free credit, rebate & commission. All credit will be forfeited subject to any violation of rules.' },
    { title: 'Every Deposit Random Bonus', bonusRequirement: 'Gucci9 members can claim unlimited times every day. Every deposit AUD 10 get random bonus. Minimum deposit AUD 10 to apply this promotion. Can play on all slot games/product. Live game and fishing game excluded. Save free game excluded.', withdrawRequirement: 'Slot unlimited bonus rollover x 1.5. Random bonus will get amount AUD 0.10 – AUD 5.00. Minimum withdraw AUD 50. Maximum withdraw amount AUD 50000.', termAndCondition: 'Register name must be same as bank. All promotion cannot combined other promotion, free credit, rebate & commission. All credit will be forfeited subject to any violation of rules.' },
    { title: 'Slot Welcome Bonus 50%', bonusRequirement: 'For new members, claim once (1) only. Minimum deposit AUD 50 to apply this promotion. Maximum bonus up to AUD 250. Can play on all slot games/product. Live game and fishing game excluded. Save free game excluded.', withdrawRequirement: 'Slot Welcome Bonus rollover x 6. Minimum withdraw turnover x 6. Maximum withdraw turnover x 100.', termAndCondition: 'Register name must be same as bank. All promotion cannot combined other promotion, free credit, rebate & commission. All credit will be forfeited subject to any violation of rules.' },
  ],
  pkm9: [
    { title: 'Slot Welcome Bonus 50%', bonusRequirement: 'For new members, claim once (1) only. Minimum deposit AUD 50 to apply this promotion. Maximum bonus up to AUD 250. Can play on all slot games/product. Live game and fishing game excluded. Save free game excluded.', withdrawRequirement: 'Slot Welcome Bonus rollover x 6. Minimum withdraw turnover x 6. Maximum withdraw turnover x 100.', termAndCondition: 'Register name must be same as bank. All promotion cannot combined other promotion, free credit, rebate & commission. All credit will be forfeited subject to any violation of rules.' },
    { title: 'Every Deposit Random Bonus', bonusRequirement: 'PKM9 member can claim unlimited times every day. Minimum deposit AUD 10 to apply this promotion. Can play on all slot games/product. Live game and fishing game excluded. Save free game excluded.', withdrawRequirement: 'Slot unlimited bonus rollover x 1.5. Random bonus will get amount AUD 0.10 – AUD 5.00. Minimum withdraw AUD 50. Maximum withdraw amount AUD 50000.', termAndCondition: 'Register name must be same as bank. All promotion cannot combined other promotion, free credit, rebate & commission. All credit will be forfeited subject to any violation of rules.' },
    { title: 'Daily Easy Step Free $100', bonusRequirement: 'All PKM9 customers can claim this bonus every day. Members are required to share their unique referral link in at least 5 different Facebook group chats. Shares to the same group will not be considered valid. Shares that are removed will not be counted. Remark: After sharing, please take a screenshot and send it to livechat for verification. Can play on WF2 these games/product. Live game and fishing game excluded. Save free game excluded.', withdrawRequirement: 'Credit must hit over AUD 1000 to unlock withdraw. Maximum withdraw AUD 20.', termAndCondition: 'Register name must be same as bank. All promotion cannot combined other promotion, free credit, rebate & commission. All credit will be forfeited subject to any violation of rules.' },
    { title: 'Daily Slot Bonus 80%', bonusRequirement: 'PKM9 member can claim once (1) every day. Minimum deposit AUD 50 to apply this promotion. Maximum bonus up to no limit. Can play on designated slot games/product. Live game and fishing game excluded. Save free game excluded.', withdrawRequirement: 'Minimum withdraw turnover x 3. Maximum withdraw turnover x 10.', termAndCondition: 'Register name must be same as bank. All promotion cannot combined other promotion, free credit, rebate & commission. All credit will be forfeited subject to any violation of rules.' },
  ],
  mrbean9: [
    { title: 'Daily Easy Step Bonus $100', bonusRequirement: 'All MrBean9 customers can claim this bonus every day. Members are required to share their unique referral link in at least 5 different Facebook groups with our poster chats. Shares to the same group will not be considered valid. Shares that are removed will not be counted. Remark: After sharing, please take a screenshot and send it to livechat for verification. Can play on WF2 these games/product. Live game and fishing game excluded. Save free game excluded.', withdrawRequirement: 'Credit must hit over AUD 1000 to unlock withdraw. Maximum withdraw AUD 20.', termAndCondition: 'Register name must be same as bank. All promotion cannot combined other promotion, free credit, rebate & commission. All credit will be forfeited subject to any violation of rules.' },
    { title: 'Monday Special Slot Bonus 60%', bonusRequirement: 'MrBean9 member can claim once (1) every Monday. Minimum deposit AUD 19 to apply this promotion. Maximum bonus up to AUD 300. Can play on all slot games/product. Live game and fishing game excluded. Save free game excluded.', withdrawRequirement: 'Slot daily bonus rollover x 4. Minimum withdraw turnover x 3. Maximum withdraw turnover x 100.', termAndCondition: 'Register name must be same as bank. All promotion cannot combined other promotion, free credit, rebate & commission. All credit will be forfeited subject to any violation of rules.' },
    { title: 'Every Deposit Random Bonus', bonusRequirement: 'MrBean9 member can claim unlimited times every day. Minimum deposit AUD 10 to apply this promotion. Can play on all slot games/product. Live game and fishing game excluded. Save free game excluded.', withdrawRequirement: 'Slot unlimited bonus rollover x 1.5. Random bonus will get amount AUD 0.10 – AUD 5.00. Minimum withdraw AUD 50. Maximum withdraw amount AUD 50000.', termAndCondition: 'Register name must be same as bank. All promotion cannot combined other promotion, free credit, rebate & commission. All credit will be forfeited subject to any violation of rules.' },
    { title: 'Daily Slot First Deposit 30%', bonusRequirement: 'MrBean9 member can claim once (1) every day. Minimum deposit AUD 10 to apply this promotion. Maximum bonus up to AUD 150. Can play on all slot games/product. Live game and fishing game excluded. Save free game excluded.', withdrawRequirement: 'Slot daily bonus rollover x 6. Minimum withdraw turnover x 5. Maximum withdraw turnover x 100.', termAndCondition: 'Register name must be same as bank. All promotion cannot combined other promotion, free credit, rebate & commission. All credit will be forfeited subject to any violation of rules.' },
  ],
  micky9: [
    { title: 'Weekly Rebate 6%', bonusRequirement: 'All members eligible. 6% rebate automatically issued every Monday (00:00:00 AM till 00:15:00 AM) to eligible Micky9 members. Weekly rebate is based on total deposit minus total withdrawal in the week (Monday 00:00:00 AM till Sunday 23:59:59 PM). Example: deposit $1000, withdraw $100 (lose $900) = $900 × 6% = $54 rebate; if you win (e.g. withdraw more than deposit), no rebate for the week. Valid on selected slot games/product (e.g. 918Kaya, Joker, ACE333, CQ9, Jili, Pegasus, Mario and others as per site). Save free game excluded.', withdrawRequirement: 'Rebate rollover x5. Minimum withdraw AUD 50. Maximum withdraw AUD 599.', termAndCondition: 'Register name must be same as bank. This promotion cannot be combined with any other promotion, free credit, rebate or commission. All credit will be forfeited subject to any violation of rules.' },
    { title: 'Weekly Commission 5%', bonusRequirement: 'All members eligible. 5% weekly commission automatically issued every Monday (12:00:00 PM) to eligible Micky9 members. Amount is based on total deposit minus total withdrawal of your all downline between this week. Valid on selected slot games/product (e.g. 918Kaya, Joker, ACE333, CQ9, Pegasus and others as per site). Save free game, live game and fishing game excluded.', withdrawRequirement: 'Commission rollover x10. Minimum withdraw AUD 50. Maximum withdraw AUD 599.', termAndCondition: 'Register name must be same as bank. This promotion cannot be combined with any other promotion, free credit, rebate or commission. All credit will be forfeited subject to any violation of rules.' },
    { title: '365 Random Daily Free', bonusRequirement: 'All members eligible. No deposit required; claim random AUD 5 – AUD 13 daily (FREE 365 DAYS BONUS). Valid on WFGaming, AFB777, EVO888H5 (slot game only). Save free game, live game and fishing game excluded.', withdrawRequirement: 'Credit must hit over AUD 399 to unlock withdraw. Maximum withdraw AUD 13.', termAndCondition: 'Register name must be same as bank. This promotion cannot be combined with any other promotion. All credit will be forfeited subject to any violation of rules.' },
    { title: 'Free Credit 103.33', bonusRequirement: 'All members eligible. No deposit required; claim AUD 103.33 once. Follow customer service steps to claim. Valid on WF Gaming, AFB777, EVO888H5 (slots only). Save free game, live game and fishing game excluded.', withdrawRequirement: 'Credit must hit over AUD 999.99 to unlock withdraw. Maximum withdraw AUD 20.', termAndCondition: 'Register name must be same as bank. Rule breach may cause credit or earnings forfeiture. This promotion cannot be combined with any other promotion. All credit will be forfeited subject to any violation of rules.' },
  ],
  winnie777: [
    { title: 'Weekly Rebate 7%', bonusRequirement: '7% rebate automatically issued every Monday (00:00 AM till 00:15 AM) to eligible Winnie777 members. Amount is based on total deposit minus total withdrawal in the week (Monday 00:00 AM till Sunday 23:59 PM). Example: lose $900 × 7% = rebate $63; if win for the week, no rebate. Valid on selected slot games/product (e.g. 918Kaya, Joker, ACE333, CQ9, Jili, Pegasus, Mario and others as per site). Save free game excluded.', withdrawRequirement: 'Bonus rollover x5. Minimum withdraw AUD 50. Maximum withdraw AUD 599.', termAndCondition: 'Register name must be same as bank. Only can apply when wallet is below AUD 1. Promotion cannot be combined with other promotion, free credit, rebate & commission. All credit will be forfeited subject to any violation of rules. Terms & conditions apply; free game saved, abnormal betting, bonus hunting or side betting may result in frozen transactions and forfeiture of balance.' },
    { title: 'Every Deposit Random Bonus', bonusRequirement: 'Winnie777 members can claim unlimited times every day. Minimum deposit AUD 10 to apply this promotion. Random bonus amount AUD 0.10 – AUD 5.00. Can play on all slot games/product. Live game and fishing game excluded. Save free game excluded.', withdrawRequirement: 'Slot unlimited bonus rollover x 1.5. Minimum withdraw AUD 50. Maximum withdraw amount AUD 50000.', termAndCondition: 'Register name must be same as bank. Promotion cannot be combined with other promotion, free credit, rebate & commission. All credit will be forfeited subject to any violation of rules. Terms & conditions apply; free game saved, abnormal betting, bonus hunting or side betting may result in frozen transactions and forfeiture of balance.' },
    { title: 'Free Credit 103.33', bonusRequirement: 'All Winnie777 members can claim AUD 103.33 once (1) time. Complete all the steps given by customer service. Valid on WF Gaming, AFB777, EVO888H5 (slot game only). Save free game, other slot games, live casino and fish game excluded.', withdrawRequirement: 'Credit must hit over AUD 999.99 to unlock withdraw. Maximum withdraw AUD 20.', termAndCondition: 'Register name must be same as bank. Only can apply when wallet is below AUD 1. Promotion cannot be combined with other promotion, free credit, rebate & commission. All credit will be forfeited subject to any violation of rules. Terms & conditions apply; free game saved, abnormal betting, bonus hunting or side betting may result in frozen transactions and forfeiture of balance.' },
    { title: '365 Random Daily Free', bonusRequirement: 'All Winnie777 members can claim random AUD 5 – AUD 13 once every day (FREE CREDIT 365 DAYS). Valid on WF Gaming, AFB777, EVO888H5 (slot game only). Save free game, other slot games, live casino and fish game excluded.', withdrawRequirement: 'Credit must hit over AUD 399 to unlock withdraw. Maximum withdraw AUD 13.', termAndCondition: 'Register name must be same as bank. Only can apply when wallet is below AUD 1. Promotion cannot be combined with other promotion, free credit, rebate & commission. All credit will be forfeited subject to any violation of rules. Terms & conditions apply; free game saved, abnormal betting, bonus hunting or side betting may result in frozen transactions and forfeiture of balance.' },
  ],
  bybid9: [
    { title: 'Apps Daily Free AUD 20', bonusRequirement: 'Claim every day. Download apps to claim. Credit hits AUD 500. Only EVENT GAME allowed. LIVE, SPORT, FISH and OTHERS not allowed.', withdrawRequirement: 'Maximum withdrawal $10 (convert deposit). Bonus amount has to meet required winover/turnover prior withdrawal.', termAndCondition: 'Available EVENT product only. Not allow to buy free games / feature win. All promotion cannot combined other promotion, deposit, rebate, commission. If caught registering multiple accounts to claim this bonus, balance will be forfeited.' },
    { title: 'Social Media Free 30$', bonusRequirement: 'Non deposit claim now. 3 times daily. Social media task required. Only EVENT GAME allowed. LIVE, SPORT, FISH and OTHERS not allowed.', withdrawRequirement: 'To unlock withdraw hit AUD 200. Max withdraw AUD 20.', termAndCondition: 'Available for event game only. Not allow to buy free games / feature win. All promotion cannot combined other promotion, deposit, rebate, commission. If caught registering multiple accounts to claim this bonus, balance will be forfeited.' },
    { title: 'Premium Jackpot $5,999', bonusRequirement: 'Min deposit AUD 50 to unlock. Get exactly bonus AUD 8.88 to win premium jackpot (receive bonus between $0.88–$8.88 randomly). Available for slot game only. LIVE, SPORT, FISH and OTHERS not allowed.', withdrawRequirement: 'To unlock withdraw hit AUD 300. $5,999 jackpot no any requirement, direct withdraw cash. Max withdraw $5,999.', termAndCondition: 'Deposit AUD 50 to unlock. Available for slot game only. Not allow to buy free games / feature win. If caught registering multiple accounts to claim this bonus, balance will be forfeited.' },
    { title: 'Daily Easy Step Free 100', bonusRequirement: 'Non deposit, claim now. 1 time daily. Only EVENT GAME allowed. LIVE, SPORT, FISH and OTHERS not allowed. Available for event game only.', withdrawRequirement: 'To unlock withdraw hit AUD 1,000. Max withdraw AUD 20. Members must join our Telegram / WhatsApp group to unlock withdraw.', termAndCondition: 'Members must join our Telegram / WhatsApp group to unlock withdraw. Available for event game only. Not allow to buy free games / feature win. All promotion cannot combined other promotion, deposit, rebate, commission. If caught registering multiple accounts to claim this bonus, balance will be forfeited.' },
  ],
  queen13: [
    { title: 'New Member Free AUD 113', bonusRequirement: 'All Queen13 members. Claim AUD 113 once (1) time. Valid for event game only. Only claim in Queen13 APP. Allow to play slot games only. Live casino, table games, arcade games and fish games excluded. Save free game, buy free spins, games features and abuse of game bugs strictly prohibited. Join Telegram for VVIP to get more free chip.', withdrawRequirement: 'Credit must hit over AUD 2000 to unlock withdraw. Maximum withdraw AUD 20.', termAndCondition: 'Register name must be same as bank. Only can apply when wallet is below AUD 1. All promotion cannot combined other promotion, free credit, rebate & commission. All credit will be forfeited subject to any violation of rules.' },
    { title: 'TPA Telegram Task Free A$35', bonusRequirement: 'Complete all tasks: join TPA channel, share TPA channel link to 5 friends, forward post about Queen13 in channel to 5 Australia Pokies groups, then screenshot and send to livechat for inspection. Valid for event game only. Allow to play slot games only. Live casino, table games, arcade games and fish games excluded. Save free game, buy free spins, games features and abuse of game bugs strictly prohibited. Join Telegram for VVIP to get more free chip.', withdrawRequirement: 'Credit must hit over AUD 500 to unlock withdraw. Maximum withdraw AUD 10.', termAndCondition: 'Register name must be same as bank. Only can apply when wallet is below AUD 1. All promotion cannot combined other promotion, free credit, deposit, rebate & commission. All credit will be forfeited subject to any violation of rules.' },
    { title: 'Weekly Rebate Bonus 6%', bonusRequirement: '6% weekly rebate automatically issued every Monday (12am) to eligible Queen13 members. Amount is based on total deposit minus total withdrawal in the week. Example: lose $9000 × 6% = rebate $540; if win for the week, no rebate. Valid to play all games/product. Save free game, buy free spins, games features and abuse of game bugs strictly prohibited. Join Telegram for VVIP to get more free chip.', withdrawRequirement: 'Bonus rollover x10. Minimum withdraw AUD 50. Maximum withdraw AUD 999.', termAndCondition: 'Register name must be same as bank. Only can apply when wallet is below AUD 0.10. All promotion cannot combined other promotion, free credit, deposit, rebate & commission. All credit will be forfeited subject to any violation of rules.' },
    { title: 'Slot Welcome Bonus 50%', bonusRequirement: 'For new members, claim once (1) only. Minimum deposit AUD 50 to apply this promotion. Maximum bonus up to AUD 250. Can play on all slot games/product. Live casino, table games, arcade game and fish games excluded. Save free game, buy free spins, games features and abuse of game bugs strictly prohibited. Join Telegram for VVIP to get more free chip.', withdrawRequirement: 'Slot Welcome Bonus rollover x 6. Minimum withdraw turnover x 6. Maximum withdraw turnover x 100.', termAndCondition: 'Register name must be same as bank. All promotion cannot combined other promotion, free credit, rebate & commission. All credit will be forfeited subject to any violation of rules.' },
  ],
  ace96au: [
    { title: '100% VVIP Bonus', bonusRequirement: '100% VVIP bonus. Example: deposit 100 AUD can get 100 AUD bonus = 200 AUD. Minimum deposit only 10 AUD. All members can claim. Only can play specified slot games. Live games and fishing games excluded.', withdrawRequirement: 'Minimum withdraw turnover x 5. Max withdraw deposit amount x 30.', termAndCondition: 'Can claim only one (1) time per member/IP/household. Cannot combine with other promotions, deposits, rebates, or commissions. Strictly NO saving of free games.' },
    { title: 'Referral Bonus AUD 5', bonusRequirement: 'Downline first deposit (AUD 20 above). Minimum deposit AUD 20 to unlock this promotion. Referral friend must register to ACE96AU via your referral link (must successful registration). Enjoy weekly downline commission 6%. Only for slot games.', withdrawRequirement: 'Can wait until AUD 28.00 above to claim it and cash out. Minimum withdraw AUD 28.00. Maximum withdraw AUD 200.00.', termAndCondition: 'Strictly NO saving of free games. Terms as per referral program.' },
    { title: 'Weekly Commission 6%', bonusRequirement: '6% weekly commission will be automatically issued every Monday at 12:00:00 PM to eligible ACE96AU members. The amount is based on the total deposit minus the total withdrawal of your entire downline between the current week.', withdrawRequirement: 'Minimum withdraw AUD 28. Maximum withdraw AUD 599.', termAndCondition: 'Only for slot games. Cannot be combined with any other promotion, deposit bonus, rebate, or commission. Strictly no saving of free games. Can be claimed only one (1) time per member, IP address, or household.' },
    { title: 'Special Rebate Bonus A$50', bonusRequirement: 'To qualify for the VIP special rebate of 50 AUD, a total deposit of 50 AUD must have been made yesterday. Only applicable for event slot games.', withdrawRequirement: 'Minimum withdraw 500 AUD. Maximum withdraw 10 AUD.', termAndCondition: 'Limited to 1 claim per day. Cannot combine with any other promotion, deposit, rebate, or commission. Strictly no saving of free games. Can be claimed only once (one) time per member/IP/household.' },
  ],
};

function buildCasino(slug: string, name: string, rating: number, summary: string, pros: string[], cons: string[]): CasinoData {
  const reviewSections = OVERVIEW_BY_SLUG[slug]
    ? OVERVIEW_BY_SLUG[slug].map((s) => ({ heading: replaceName(s.heading, name), content: replaceName(s.content, name) }))
    : SHARED.reviewSections.map((s) => ({ heading: replaceName(s.heading, name), content: replaceName(s.content, name) }));
  const bonuses = BONUSES_BY_SLUG[slug] ?? SHARED.bonuses;
  return {
    slug,
    name,
    logo: getBonusLogoUrl(slug),
    banner: SHARED.banner,
    rating,
    playNowUrl: AFFILIATE_URL_BY_SLUG[slug] ?? `https://${slug}.com`,
    summary,
    pros,
    cons,
    trustBadges: SHARED.trustBadges,
    license: SHARED.license,
    withdrawalLimit: WITHDRAWAL_LIMIT_BY_SLUG[slug] ?? 'See site for details',
    trustScoreBy: SHARED.trustScoreBy,
    trustLabel: SHARED.trustLabel,
    keyFacts: SHARED.keyFacts,
    bonuses,
    games: SHARED.games,
    banking: SHARED.banking,
    review: SHARED.review.map((r) => ({ ...r, content: r.content.replace(/Sugar96 Casino|Sugar96|this casino/gi, name) })),
    reviewSections,
  };
}

const LIST: Array<{ slug: string; name: string; rating: number; summary: string; pros: string[]; cons: string[] }> = [
  { slug: 'ipay9', name: 'iPay9', rating: 4.8, summary: 'iPay9 offers a strong mix of pokies, table games, and fast payouts. Australian-friendly with 24/7 support.', pros: ['Clear and fair terms and conditions with no predatory clauses', 'Strong game diversity across slots, table games, and live dealer', 'Fast withdrawal processing with no maximum limit for eligible methods', 'Licensed and regulated for player protection', '24/7 customer support for Australian players'], cons: ['Bonus offers are subject to wagering requirements', 'Service may be restricted in certain regions'] },
  { slug: 'kingbet9', name: 'Kingbet9', rating: 4.7, summary: 'KingBet9 brings top games, competitive bonuses, and crypto-friendly banking. Built for the Australian market.', pros: ['Accepts major cryptocurrencies alongside traditional banking', 'Fast withdrawal times with transparent processing', 'Mobile-first platform with full functionality on all devices', 'Wide selection of pokies and table games from top providers', 'Competitive welcome and reload bonuses'], cons: ['Wagering requirements apply to bonus funds', 'Live dealer catalogue is smaller than some competitors'] },
  { slug: 'bigpay77', name: 'Bigpay77', rating: 4.8, summary: 'Bigpay77 is a trusted online casino with no withdrawal limits, generous bonuses, and a wide game range.', pros: ['Trusted operator with a solid reputation for paying players', 'No maximum withdrawal limit (ideal for high rollers)', 'Wide range of bonuses and ongoing promotions', 'Large game library including slots, table games, and live casino', 'Multiple secure payment options including bank and crypto'], cons: ['Promotional offers carry standard wagering terms', 'Some geographic restrictions may apply'] },
  { slug: 'me99', name: 'Me99', rating: 4.5, summary: 'Me99 accepts fiat and crypto with live dealer and a solid game library. Good for casual and regular players.', pros: ['Accepts both fiat and cryptocurrency for deposits and withdrawals', 'Live dealer games available for a real-casino experience', 'Simple, user-friendly interface suitable for all experience levels', 'Solid game library with popular titles', 'Quick sign-up and verification process'], cons: ['Fewer game providers compared to larger casinos', 'Standard wagering requirements on bonuses'] },
  { slug: 'rolex9', name: 'Rolex9', rating: 4.7, summary: 'Rolex9 delivers a premium experience with a wide game range, daily rebates, and reliable support.', pros: ['Premium design and user experience throughout the site', 'Wide game range including pokies, table games, and live dealer', 'Daily rebates and weekly rewards for active players', 'Reliable customer support and transparent operations', 'Strong banking options with fast processing'], cons: ['Bonuses are subject to wagering requirements', 'Not available in all jurisdictions'] },
  { slug: 'gucci9', name: 'Gucci9', rating: 4.6, summary: 'Gucci9 is fully licensed with multiple payment options and a strong focus on security and fairness.', pros: ['Fully licensed and regulated for fair play', 'Multiple payment options including cards, e-wallets, and crypto', 'Strong focus on security and responsible gaming', 'Clear and fair terms and conditions', 'SSL encryption and secure account handling'], cons: ['Bonus funds are subject to wagering terms', 'Live casino offering is more limited than slots'] },
  { slug: 'pkm9', name: 'PKM9', rating: 4.5, summary: 'PKM9 offers popular brands and a mobile-friendly platform with regular new releases and promotions.', pros: ['Popular game brands and well-known providers', 'Mobile-friendly platform with smooth performance', 'Regular new game releases and seasonal promotions', 'Straightforward terms and competitive bonus offers', 'Good mix of pokies and table games'], cons: ['Standard terms and conditions apply to promotions', 'Service restricted in some regions'] },
  { slug: 'mrbean9', name: 'MrBean9', rating: 4.4, summary: 'MrBean9 combines a fun theme with quick payouts and a solid selection of pokies and table games.', pros: ['Fun, themed design that is easy to navigate', 'Quick payout processing for verified accounts', 'Easy sign-up and low barrier to start playing', 'Solid selection of pokies and table games', 'Friendly customer support'], cons: ['Bonuses carry wagering requirements', 'Fewer game providers than larger operators'] },
  { slug: 'micky9', name: 'Micky9', rating: 4.7, summary: 'Micky9 is licensed by the Curacao Gaming Authority (CGA) with support for leading Australian banks and a wide game and bonus range.', pros: ['Licensed by the Curacao Gaming Authority (CGA)', 'Support for leading Australian banks and local payment methods', 'Wide range of games and bonus offers', 'Transparent operations and clear terms', 'Strong focus on the Australian market'], cons: ['Wagering terms apply to promotional offers', 'Not available in all countries'] },
  { slug: 'winnie777', name: 'Winnie777', rating: 4.8, summary: 'Winnie777 provides generous bonuses, 24/7 support, and a large library of pokies and live games.', pros: ['Generous welcome and ongoing bonuses', '24/7 customer support for players', 'Large library of pokies and live dealer games', 'No maximum withdrawal limit for eligible methods', 'Wide payment options including crypto'], cons: ['Promotions are subject to wagering requirements', 'Some withdrawal limits may apply by method'] },
  { slug: 'bybid9', name: 'Bybid9', rating: 4.6, summary: 'Bybid9 offers no withdrawal limits, strong responsible gaming tools, and daily and weekly rewards.', pros: ['No maximum withdrawal limit for eligible payment methods', 'Strong responsible gaming tools and limits', 'Daily and weekly rebates and rewards', 'Clear terms and fair bonus conditions', 'Multiple banking and crypto options'], cons: ['Bonus funds are subject to wagering terms', 'Regional restrictions may apply'] },
  { slug: 'queen13', name: 'Queen13', rating: 4.7, summary: 'Queen13 combines premium design with fast support and a solid mix of bonuses and games.', pros: ['Premium design and smooth user experience', 'Fast support response and helpful team', 'Good mix of bonuses and regular promotions', 'Solid game selection from reputable providers', 'Secure payments and transparent policies'], cons: ['Wagering requirements apply to bonus offers', 'Not available in all regions'] },
  { slug: 'ace96au', name: 'Ace96au', rating: 4.7, summary: 'Ace96au focuses on Australian players with a trusted brand, local payment options, and strong support.', pros: ['Focused on Australian players with local payment options', 'Trusted brand with a reputation for reliability', 'Support for Australian banks and popular e-wallets', 'Strong customer support and clear communication', 'Fair terms and a good game range'], cons: ['Bonuses are subject to standard wagering terms', 'Withdrawal limits may apply depending on method'] },
];

export const casinoDatabase: Record<string, CasinoData> = Object.fromEntries(
  LIST.map((c) => [c.slug, buildCasino(c.slug, c.name, c.rating, c.summary, c.pros, c.cons)])
);

export const getCasinoBySlug = (slug: string): CasinoData | undefined => {
  return casinoDatabase[slug];
};

export const getAllCasinoSlugs = (): string[] => {
  return Object.keys(casinoDatabase);
};
